name: Run units
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - feat/**
jobs:
  run-units:
    runs-on: my-ubuntu
    steps:
      - uses: actions/checkout@v1

      - name: Run units
        run: bb -f ./.github/common-scripts/run-units.clj
